services:
  # Backend API Service
  - type: web
    name: property-aggregator-backend
    env: docker
    region: Singapore
    plan: free
    rootDirectory: backend
    dockerfilePath: Dockerfile  # Removed ./ prefix
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://property-user:potro5-wezfuR-kekqyx@property-agregator.mxho0nz.mongodb.net/property-aggregator?retryWrites=true&w=majority&appName=Property-Agregator
      - key: GEMINI_API_KEY
        value: AIzaSyCBL_ZIIX5-SWCUd0TImo4IwuaNVYTwYWc
      - key: CORS_ORIGIN
        value: https://property-aggregator-frontend.onrender.com

  # Frontend Service (Static Site)
  - type: web
    name: property-aggregator-frontend
    env: static
    region: Singapore
    plan: free
    buildCommand: npm run install:all && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://property-aggregator-backend.onrender.com/api