services:
  # Backend API Service
  - type: web
    name: property-aggregator-backend
    env: docker
    region: Singapore  # Corrected capitalization
    plan: free
    rootDirectory: backend
    buildCommand: docker build -t property-backend .
    startCommand: docker run -p 5001:5001 property-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://property-user:potro5-wezfuR-kekqyx@property-agregator.mxho0nz.mongodb.net/property-aggregator?retryWrites=true&w=majority&appName=Property-Agregator
      - key: GEMINI_API_KEY
        value: AIzaSyCBL_ZIIX5-SWCUd0TImo4IwuaNVYTwYWc

  # Frontend Service
  - type: web
    name: property-aggregator-frontend
    env: docker
    region: Singapore  # Corrected capitalization
    plan: free
    rootDirectory: frontend
    buildCommand: docker build -t property-frontend .
    startCommand: docker run -p 80:80 property-frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://property-aggregator-backend.onrender.com/api